apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-image-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx      # This is required , initially i missed this properlly and not able to 
  rules:
  - host: web.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: web-image-service
            port: 
              number: 80
